packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^3.0.1
  '@ai-sdk/react': ^2.0.39
  '@base-ui/react': ^1.0.0
  '@biomejs/biome': 2.3.10
  '@hono/node-server': ^1.14.4
  '@hookform/resolvers': ^5.1.1
  '@opentui/core': ^0.1.63
  '@opentui/react': ^0.1.63
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@tailwindcss/vite': ^4.0.15
  '@tanstack/react-form': ^1.12.3
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': 5.91.2
  '@tanstack/react-router': ^1.141.1
  '@tanstack/react-router-devtools': 1.144.0
  '@tanstack/router-plugin': ^1.141.1
  '@vitejs/plugin-react': ^4.3.4
  '@wxt-dev/module-react': ^1.1.5
  ai: ^6.0.3
  ansi-to-html: ^0.7.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.2
  hono: ^4.11.3
  husky: ^9.1.7
  lint-staged: ^16.1.2
  lucide-react: ^0.473.0
  next-themes: ^0.4.6
  postcss: ^8.5.3
  shadcn: ^3.6.2
  sonner: ^2.0.5
  streamdown: ^1.6.10
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.0.15
  tsdown: ^0.16.5
  tsx: ^4.19.2
  turbo: ^2.6.3
  tw-animate-css: ^1.2.5
  typescript: ^5
  ultracite: 6.5.0
  vite: ^6.2.2
  wxt: ^0.20.6
  zod: ^4.1.13

onlyBuiltDependencies:
  - spawn-sync
